//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.DisplayText", typeof(DisplayText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like that name. Choose another one..
        /// </summary>
        public static string Error_InvalidName {
            get {
                return ResourceManager.GetString("Error_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have none left. Choose a different one..
        /// </summary>
        public static string Error_NoBalls {
            get {
                return ResourceManager.GetString("Error_NoBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embark on a new adventure to become a Pokemon master! Navigate through the maps and encounter different pokemon. If a pokemon appears, hurry! You only have a few seconds before it disappears!.
        /// </summary>
        public static string Game_Description {
            get {
                return ResourceManager.GetString("Game_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your adventure is about to begin....
        /// </summary>
        public static string InGame_Begin {
            get {
                return ResourceManager.GetString("InGame_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a boy or are you a girl?.
        /// </summary>
        public static string InGame_Player_Gender {
            get {
                return ResourceManager.GetString("InGame_Player_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And what is your name?.
        /// </summary>
        public static string InGame_Player_Name {
            get {
                return ResourceManager.GetString("InGame_Player_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to embark on a pokemon adventure?!.
        /// </summary>
        public static string InGame_Ready {
            get {
                return ResourceManager.GetString("InGame_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a choice of 3 starter pokemon!.
        /// </summary>
        public static string InGame_Starter {
            get {
                return ResourceManager.GetString("InGame_Starter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pokemon Forms!.
        /// </summary>
        public static string InGame_Welcome {
            get {
                return ResourceManager.GetString("InGame_Welcome", resourceCulture);
            }
        }
    }
}
